[package]
name = "zappy-cli"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

description = "Zappy - Clap CLI, prompts, logging, UX"

[dependencies]
zappy-core.workspace = true
zappy-fs.workspace = true
clap.workspace = true
serde.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
    "zappy",
    "zappy-adapters",
    "zappy-cli",
    "zappy-core",
    "zappy-fs",
    "zappy-hooks"
]
development = ["criterion", "pretty_assertions"]
