[workspace]
members = [
    "./",
    "crates/zappy-adapters",
    "crates/zappy-cli",
    "crates/zappy-core",
    "crates/zappy-fs",
    "crates/zappy-hooks",
]
resolver = "2"

[workspace.package]
authors                 = ["mrbya <v.toth.svk2@gmail.com>"]
description             = "An electrifying project templating engine"
edition                 = "2024"
rust-version            = "1.85.0"
homepage                = "https://gitlab.com/byacrates/zappy.git"
repository              = "https://gitlab.com/byacrates/zappy.git"
license                 = "MIT OR Apache-2.0"
keywords                = ["zappy", "templates", "scaffolding"]
categories              = ["command-line-utilities"]
version                 = "0.0.1-pre"

[package]
name                    = "zappy"
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description.workspace   = true
version.workspace       = true
publish                 = true

[workspace.dependencies]
# Zappy crates
zappy-adapters          = { path = "crates/zappy-adapters" }
zappy-cli               = { path = "crates/zappy-cli" }
zappy-core              = { path = "crates/zappy-core" }
zappy-fs                = { path = "crates/zappy-fs" }
zappy-hooks             = { path = "crates/zappy-hooks" }
# Other workspace deps
clap                    = { version = "4", features = ["derive"] }
camino                  = { version = "1", features = ["serde1"] }
indexmap                = { version = "2", features = ["serde"] }
serde                   = { version = "1", features = ["derive"] }
thiserror               = { version = "2" }
toml                    = { version = "1" }
directories             = { version = "6" }
tempfile                = { version = "3" }
assert_cmd              = { version = "2" }
predicates              = { version = "3" }
heck                    = { version = "0.5" }

[dependencies]
zappy-cli.workspace = true

[dev-dependencies]
criterion = "0.8"
pretty_assertions = "1"
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[features]
default = []
full = []

[lib]
bench = false

[[bin]]
name = "zappy"
path = "src/main.rs"
bench = false

[package.metadata.cargo-udeps.ignore]
normal = [
    "zappy",
    "zappy-adapters",
    "zappy-cli",
    "zappy-core",
    "zappy-fs",
    "zappy-hooks"
]
development = ["criterion", "pretty_assertions"]

[package.metadata.playground]
features = ["full"]

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false

