[workspace]
members = [

]
resolver = "2"

[wroskpace.package]
authors = ["mrbya <v.toth.svk2@gmail.com>"]
description = "An electrifying project templating engine"
edition = "2024"
rust-version = "1.85.0"
homepage = "https://gitlab.com/byacrates/zappy.git"
repository = "https://gitlab.com/byacrates/zappy.git"
license = "MIT OR Apache-2.0"
keywords = ["zappy", "templates", "scaffolding"]
categories = ["command-line-utilities"]
version = "0.0.1-pre"

[workspace.dependencies]

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false
