// TODO: Add built-in variable spec construction, resolution and injection.

use indexmap::IndexMap;

use crate::{apply_transform, TransformKind, VariableValueMap};

// Reserved variable names owned by Zappy.
/// Project name variable name.
pub const PROJECT_NAME: &str = "project_name";
/// Project user variable name.
pub const USER: &str = "user";
/// Project user email variable name.
pub const EMAIL: &str = "email";
/// Generation date variable name.
pub const DATE: &str = "date";
/// Generation date day variable name.
pub const DAY: &str = "day";
/// Generation date month variable name.
pub const MONTH: &str = "month";
/// Generation date year variable name.
pub const YEAR: &str = "year";

/// All cannonica built-in names.
pub const BUILTIN_NAMES: &[&str] = &[PROJECT_NAME, USER, EMAIL, DATE, DAY, MONTH, YEAR];

/// Built-in transforms generated by zappy.
pub const BUILTIN_TRANSFORMS: &[TransformKind] = &[
    TransformKind::Raw,
    TransformKind::Kebab,
    TransformKind::Snake,
    TransformKind::Pascal,
    TransformKind::Camel,
    TransformKind::ScreamingSnake,
    TransformKind::Upper,
    TransformKind::Lower,
];

/// Returns true if the name is reserved for a built-in variable.
#[must_use]
pub fn is_builtin_name(name: &str) -> bool {
    matches!(
        name,
        PROJECT_NAME | USER | EMAIL | DATE | DAY | MONTH | YEAR
    )
}

/// Returns true if all provided keys are known built-ins.
#[must_use]
pub fn are_builtin_names(values: &VariableValueMap) -> bool {
    values.keys().all(|name| is_builtin_name(name))
}

/// Generate transformed values for built-ins.
#[must_use]
pub fn builtin_transformations(
    values: &VariableValueMap,
) -> IndexMap<String, IndexMap<TransformKind, String>> {
    let mut transformations = IndexMap::new();

    for (name, value) in values {
        if !is_builtin_name(name) {
            continue;
        }

        let mut transformed = IndexMap::new();

        for transform in BUILTIN_TRANSFORMS {
            transformed.insert(*transform, apply_transform(value, *transform));
        }

        transformations.insert(name.clone(), transformed);
    }

    transformations
}

/// Generates placeholder replacements for built-ins.
#[must_use]
pub fn builtin_replacements(values: &VariableValueMap) -> IndexMap<String, String> {
    let transformations = builtin_transformations(values);
    let mut replacements = IndexMap::new();

    for (name, transformed_values) in transformations {
        for (transform, value) in transformed_values {
            replacements.insert(builtin_placeholder(&name, transform), value);
        }
    }

    replacements
}

/// Returns the engine-defined placeholder for a built-in transform.
#[must_use]
pub fn builtin_placeholder(name: &str, transform: TransformKind) -> String {
    let base = builtin_placeholder_base(name);

    match transform {
        TransformKind::Raw => format!("__ZAPPY_{base}__"),
        TransformKind::Kebab => format!("__ZAPPY_{base}_KEBAB__"),
        TransformKind::Snake => format!("__ZAPPY_{base}_SNAKE__"),
        TransformKind::Pascal => format!("__ZAPPY_{base}_PASCAL__"),
        TransformKind::Camel => format!("__ZAPPY_{base}_CAMEL__"),
        TransformKind::ScreamingSnake => format!("__ZAPPY_{base}_SCREAMING__"),
        TransformKind::Upper => format!("__ZAPPY_{base}_UPPER__"),
        TransformKind::Lower => format!("__ZAPPY_{base}_LOWER__"),
    }
}

/// Return uppercase placeholder base.
fn builtin_placeholder_base(name: &str) -> String {
    name.to_uppercase()
}
