[package]
name = "__ZAPPY_PROJECT_NAME_KEBAB__-core"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "__ZAPPY_PROJECT_NAME__ - core API"

[dependencies]

[dev-dependencies]

[package.metadata.cargo-udeps.ignore]
normal = [
    "__ZAPPY_PROJECT_NAME_KEBAB__",
    "__ZAPPY_PROJECT_NAME_KEBAB__-shell",
]
development = ["criterion", "pretty_assertions"]
