# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
    files: ^(?!\.gitlab-ci\.yml$).*\.ya?ml$

  - id: pretty-format-json
  - id: check-added-large-files

- repo: https://github.com/matthorgan/pre-commit-conventional-commits
  rev: 20fb9631be1385998138432592d0b6d4dfa38fc9
  hooks:
  - id: conventional-commit-check
    stages:
    - commit-msg

- repo: local
  hooks:
      - id: pre-commit-rs
        name: rust formatting, linter checks and tests
        language: unsupported
        entry: just ci
        pass_filenames: false
        files: >
          (?x)^(
            .*\.(rs|toml)|
            justfile
          )$

      - id: readme
        name: readme re-indexing
        language: unsupported
        entry: just index
        pass_filenames: false
        files: .*README.md
