[workspace]
members = [
    "./",
    "crates/__ZAPPY_PROJECT_NAME_KEBAB__-shell",
    "crates/__ZAPPY_PROJECT_NAME_KEBAB__-core",
]
resolver = "2"

[workspace.package]
authors                 = ["__AUTHOR__ <__EMAIL__>"]
description             = "__DESCRIPTION__"
edition                 = "2024"
rust-version            = "1.85.0"
homepage                = "__REPO__"
repository              = "__REPO__"
license                 = "MIT OR Apache-2.0"
keywords                = ["__ZAPPY_PROJECT_NAME_KEBAB__", "cli"]
categories              = ["command-line-utilities"]
version                 = "0.0.1"

[package]
name                    = "__ZAPPY_PROJECT_NAME_KEBAB__"
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description.workspace   = true
version.workspace       = true
publish                 = true

[workspace.dependencies]
# __ZAPPY_PROJECT_NAME__ crates
__ZAPPY_PROJECT_NAME_KEBAB__-shell  = { path = "crates/__ZAPPY_PROJECT_NAME_KEBAB__-shell" }
__ZAPPY_PROJECT_NAME_KEBAB__-core   = { path = "crates/__ZAPPY_PROJECT_NAME_KEBAB__-core" }
# Other workspace deps
clap                    = { version = "4", features = ["derive"] }
criterion               = { version = "0.8" }
pretty_assertions       = { version = "1" }
assert_cmd              = { version = "2" }
predicates              = { version = "3" }

[dependencies]
__ZAPPY_PROJECT_NAME_KEBAB__-shell.workspace = true

[dev-dependencies]
criterion.workspace = true
pretty_assertions.workspace = true
assert_cmd.workspace = true
predicates.workspace = true

[features]
default = []
full = []

# [lib]
# bench = false

[[bin]]
name = "__ZAPPY_PROJECT_NAME_KEBAB__"
path = "src/main.rs"
bench = false

[[bench]]
name = "benches"
harness = false
required-features = ["full"]

[package.metadata.cargo-udeps.ignore]
normal = [
    "__ZAPPY_PROJECT_NAME_KEBAB__",
]
development = ["criterion", "pretty_assertions"]

[package.metadata.playground]
features = ["full"]

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false
