# Template metadata.
[template]
id = "cpp-cmake-lib"
name = "C++ CMake library"
description = "C++ static library managed by CMake build system"
language = "cpp"
version = "0.1.0"

# Template source directory.
[template.source]
root = "template"

# Template variable definitions.
[variables]
description = {
    required = true,
    default = "TODO: add project description",
    placeholders = {
        raw = "__DESCRIPTION__",
    }
}

use_gitlab_ci = {
    default = false,
}

gitlab_image_registry = {
    default = "{TODO: add gitlab image registry}",
    required_when = "use_gitlab_ci",
    placeholders = {
        raw = "__GITLAB_IMAGE_REGISTRY__",
    }
}

# Template file path config.
[paths]
exclude = [".git", ".DS_Store", "build"]
binary_extensions = ["png", "jpg", "jpeg", "gif", "ico", "pdf", "zip", ".cmake"]
binary_files = [
    "gtestsetup/.gitignore",
    "gtestsetup/CMakeLists.txt",
    "gtestsetup/gtestsetup.cmake",
    "gtestsetup/LICENSE",
    "gtestsetup/README.md"
]

[[conditionals]]
path = ".gitlab-ci.yml"
when = "use_gitlab_ci"

[[conditionals]]
path = "Dockerfile"
when = "use_gitlab_ci"

# Template validation config.
[validation]
output_dir_name = "zappy-cpp-cmake-lib"
variables = {
    description = "Generated C++ CMake app",
}

# Validation setup hooks.
[[validation.setup]]
name = "create build dir"
command = "mkdir"
args = ["build"]

# Validation process steps.
[[validation.steps]]
name = "configure project"
working_dir = "build"
command = "cmake"
args = ["..", "-GNinja", "-DZAPPY_CPP_CMAKE_LIB_BUILD_EXAMPLES=ON"]

[[validation.steps]]
name = "build project"
working_dir = "build"
command = "ninja"
args = []

[[validation.steps]]
name = "test project"
working_dir = "build"
command = "ninja"
args = ["test"]

[[validation.steps]]
name = "run example"
working_dir = "build"
command = "ninja"
args = ["run_greeting"]
