[package]
name = "zappy-fs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

description = "Zappy - Safe filesystem ops"

[dependencies]
zappy-core.workspace = true
directories.workspace = true
thiserror.workspace = true
heck.workspace = true

[dev-dependencies]
tempfile.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
    "zappy",
    "zappy-adapters",
    "zappy-cli",
    "zappy-core",
    "zappy-fs",
    "zappy-hooks",
    "zappy-templates"
]
development = ["criterion", "pretty_assertions"]
