# Template metadata.
[template]
id = "lua-cli"
name = "Lua CLI app"
description = "Luarock-bundled Lua-based CLI application using argparse."
language = "lua"
version = "0.1.0"

# Template source directory.
[template.source]
root = "template"

# Template variable definitions.
[variables]
description = {
    required = true,
    default = "{TODO: add project description}",
    placeholders = {
        raw = "__DESCRIPTION__",
    }
}

use_gitlab_ci = {
    default = false,
}

gitlab_image_registry = {
    prompt = "Gitlab image registry",
    required_when = "use_gitlab_ci",
    placeholders = {
        raw = "__GITLAB_IMAGE_REGISTRY__",
    }
}

# Template file path config.
[paths]
exclude = [".git", ".DS_Store", "target", "node_modules"]
binary_extensions = ["png", "jpg", "jpeg", "gif", "ico", "pdf", "zip"]
binary_files = []

# Conditional include paths.
[[conditionals]]
path = ".gitlab.ci-yml"
when = "use_gitlab_ci"

# Template generation hooks
[hooks]

# Template validation config.
# [validation]
# output_dir_name = "zappy-validation-luarock"
# variables = {
#     test_var = "validation test var value",
#     include_optional = true,
# }

# Validation setup hooks.
# [[validation.setup]]

# Validation process steps.
# [[validation.steps]]

# Validation teardown hooks.
# [[validation.teardown]]
