name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Just
        run: cargo install just

      - name: Bootstrap
        run: just init

      - name: Test
        run: just ci
