image: __GITLAB_IMAGE_REGISTRY__:latest

stages:
  - build
  - test
  - coverage
  - examples

before_script:
  - git submodule update --init

build:
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake .. -GNinja
    - ninja
  artifacts:
    paths:
      - build/

test:
  stage: test
  dependencies:
    - build
  script:
    - cd build
    - ninja test
  artifacts:
    paths:
      - build/

coverage:
  stage: coverage
  dependencies:
    - test
  script:
    - cd build
    - ninja cov
  artifacts:
    paths:
      - build/coverage.info

examples:
  stage: examples
  dependencies:
    - test
  script:
    - mkdir -p build && cd build
    - cmake .. -GNinja -D__ZAPPY_PROJECT_NAME_SCREAMING___BUILD_EXAMPLES=ON
    - ninja
